%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Volumes/labs-1/NPC/Analysis/T1000/data-organized-neworg/AA081/T0/behavioral_session/AA081-T0-__BH-R1-_BEH.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/02/03 12:20:25
function AA081T0BHR1BEH = impBEH_BH(filename)
%% Initialize variables.
delimiter = ',';
startRow = 3;

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,9,11,13,15,17,19,21,23,25]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,3,4,5,6,9,11,13,15,17,19,21,23,25]);
rawCellColumns = raw(:, [7,8,10,12,14,16,18,20,22,24]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
AA081T0BHR1BEH = table;
AA081T0BHR1BEH.trial_number = cell2mat(rawNumericColumns(:, 1));
AA081T0BHR1BEH.trial_type = cell2mat(rawNumericColumns(:, 2));
AA081T0BHR1BEH.event_code = cell2mat(rawNumericColumns(:, 3));
AA081T0BHR1BEH.absolute_time = cell2mat(rawNumericColumns(:, 4));
AA081T0BHR1BEH.response_time = cell2mat(rawNumericColumns(:, 5));
AA081T0BHR1BEH.response = cell2mat(rawNumericColumns(:, 6));
AA081T0BHR1BEH.result = rawCellColumns(:, 1);
AA081T0BHR1BEH.VarName8 = rawCellColumns(:, 2);
AA081T0BHR1BEH.VarName9 = cell2mat(rawNumericColumns(:, 7));
AA081T0BHR1BEH.VarName10 = rawCellColumns(:, 3);
AA081T0BHR1BEH.VarName11 = cell2mat(rawNumericColumns(:, 8));
AA081T0BHR1BEH.VarName12 = rawCellColumns(:, 4);
AA081T0BHR1BEH.VarName13 = cell2mat(rawNumericColumns(:, 9));
AA081T0BHR1BEH.VarName14 = rawCellColumns(:, 5);
AA081T0BHR1BEH.VarName15 = cell2mat(rawNumericColumns(:, 10));
AA081T0BHR1BEH.VarName16 = rawCellColumns(:, 6);
AA081T0BHR1BEH.VarName17 = cell2mat(rawNumericColumns(:, 11));
AA081T0BHR1BEH.VarName18 = rawCellColumns(:, 7);
AA081T0BHR1BEH.VarName19 = cell2mat(rawNumericColumns(:, 12));
AA081T0BHR1BEH.VarName20 = rawCellColumns(:, 8);
AA081T0BHR1BEH.VarName21 = cell2mat(rawNumericColumns(:, 13));
AA081T0BHR1BEH.VarName22 = rawCellColumns(:, 9);
AA081T0BHR1BEH.VarName23 = cell2mat(rawNumericColumns(:, 14));
AA081T0BHR1BEH.VarName24 = rawCellColumns(:, 10);
AA081T0BHR1BEH.VarName25 = cell2mat(rawNumericColumns(:, 15));

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp me rawNumericColumns rawCellColumns R;